server:
  port: 9002
keycloak:
  realm: cloud-app
  bearer-only: true
  auth-server-url: http://10.1.11.129:8080/auth
  ssl-required: none
  resource: backend
  use-resource-role-mappings: false
  principal-attribute: preferred_username
logging:
  level:
    org: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.11.129:3306/cloud-app?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
    username: root
    password: root
  flyway:
    enabled: false